//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string btn_Add {
            get {
                return ResourceManager.GetString("btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加维修项目 的本地化字符串。
        /// </summary>
        public static string btn_AddNewService {
            get {
                return ResourceManager.GetString("btn_AddNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核出库 的本地化字符串。
        /// </summary>
        public static string btn_Approve {
            get {
                return ResourceManager.GetString("btn_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 费用管理 的本地化字符串。
        /// </summary>
        public static string btn_ChargeManagement {
            get {
                return ResourceManager.GetString("btn_ChargeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户管理 的本地化字符串。
        /// </summary>
        public static string btn_CustomerManagement {
            get {
                return ResourceManager.GetString("btn_CustomerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按日期查询 的本地化字符串。
        /// </summary>
        public static string btn_DateSearch {
            get {
                return ResourceManager.GetString("btn_DateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string btn_Load {
            get {
                return ResourceManager.GetString("btn_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进货入库 的本地化字符串。
        /// </summary>
        public static string btn_NewPurchase {
            get {
                return ResourceManager.GetString("btn_NewPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售开单 的本地化字符串。
        /// </summary>
        public static string btn_NewSale {
            get {
                return ResourceManager.GetString("btn_NewSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string btn_Print {
            get {
                return ResourceManager.GetString("btn_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货品管理 的本地化字符串。
        /// </summary>
        public static string btn_ProductManagement {
            get {
                return ResourceManager.GetString("btn_ProductManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货品统计 的本地化字符串。
        /// </summary>
        public static string btn_ProductReport {
            get {
                return ResourceManager.GetString("btn_ProductReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库管理 的本地化字符串。
        /// </summary>
        public static string btn_PurchaseManagement {
            get {
                return ResourceManager.GetString("btn_PurchaseManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库报表 的本地化字符串。
        /// </summary>
        public static string btn_PurchaseReportManagement {
            get {
                return ResourceManager.GetString("btn_PurchaseReportManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string btn_Refresh {
            get {
                return ResourceManager.GetString("btn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售管理 的本地化字符串。
        /// </summary>
        public static string btn_SaleManagement {
            get {
                return ResourceManager.GetString("btn_SaleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售报表 的本地化字符串。
        /// </summary>
        public static string btn_SaleReportManagement {
            get {
                return ResourceManager.GetString("btn_SaleReportManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存并新增 的本地化字符串。
        /// </summary>
        public static string btn_SaveAndNew {
            get {
                return ResourceManager.GetString("btn_SaveAndNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维修项目管理 的本地化字符串。
        /// </summary>
        public static string btn_ServiceManagement {
            get {
                return ResourceManager.GetString("btn_ServiceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商管理 的本地化字符串。
        /// </summary>
        public static string btn_SupplierManagement {
            get {
                return ResourceManager.GetString("btn_SupplierManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新配件成本价 的本地化字符串。
        /// </summary>
        public static string btn_UpdateCostPrice {
            get {
                return ResourceManager.GetString("btn_UpdateCostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string column_Address {
            get {
                return ResourceManager.GetString("column_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否已审核 的本地化字符串。
        /// </summary>
        public static string column_Approved {
            get {
                return ResourceManager.GetString("column_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经办人 的本地化字符串。
        /// </summary>
        public static string column_AttendantName {
            get {
                return ResourceManager.GetString("column_AttendantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别 的本地化字符串。
        /// </summary>
        public static string column_Category {
            get {
                return ResourceManager.GetString("column_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 费用名称 的本地化字符串。
        /// </summary>
        public static string column_ChargeName {
            get {
                return ResourceManager.GetString("column_ChargeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人 的本地化字符串。
        /// </summary>
        public static string column_Contact {
            get {
                return ResourceManager.GetString("column_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成本价 的本地化字符串。
        /// </summary>
        public static string column_CostPrice {
            get {
                return ResourceManager.GetString("column_CostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称 的本地化字符串。
        /// </summary>
        public static string column_CustomerName {
            get {
                return ResourceManager.GetString("column_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string column_Date {
            get {
                return ResourceManager.GetString("column_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单号 的本地化字符串。
        /// </summary>
        public static string column_DH {
            get {
                return ResourceManager.GetString("column_DH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发动机编号 的本地化字符串。
        /// </summary>
        public static string column_EngineID {
            get {
                return ResourceManager.GetString("column_EngineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string column_ID {
            get {
                return ResourceManager.GetString("column_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整机编号 的本地化字符串。
        /// </summary>
        public static string column_MachineID {
            get {
                return ResourceManager.GetString("column_MachineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备厂家 的本地化字符串。
        /// </summary>
        public static string column_ManufacturerName {
            get {
                return ResourceManager.GetString("column_ManufacturerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string column_Note {
            get {
                return ResourceManager.GetString("column_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string column_Number {
            get {
                return ResourceManager.GetString("column_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 厂码 的本地化字符串。
        /// </summary>
        public static string column_PDM {
            get {
                return ResourceManager.GetString("column_PDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话号码 的本地化字符串。
        /// </summary>
        public static string column_PhoneNumber {
            get {
                return ResourceManager.GetString("column_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金额 的本地化字符串。
        /// </summary>
        public static string column_Price {
            get {
                return ResourceManager.GetString("column_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车型/发动机 的本地化字符串。
        /// </summary>
        public static string column_ProductCategory {
            get {
                return ResourceManager.GetString("column_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配件名称 的本地化字符串。
        /// </summary>
        public static string column_ProductName {
            get {
                return ResourceManager.GetString("column_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配件利润 的本地化字符串。
        /// </summary>
        public static string column_ProductProfit {
            get {
                return ResourceManager.GetString("column_ProductProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拼音简码 的本地化字符串。
        /// </summary>
        public static string column_PY {
            get {
                return ResourceManager.GetString("column_PY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售单价 的本地化字符串。
        /// </summary>
        public static string column_SaleUnitPrice {
            get {
                return ResourceManager.GetString("column_SaleUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维修项目 的本地化字符串。
        /// </summary>
        public static string column_Service {
            get {
                return ResourceManager.GetString("column_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总金额 的本地化字符串。
        /// </summary>
        public static string column_Sum {
            get {
                return ResourceManager.GetString("column_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成本价合计 的本地化字符串。
        /// </summary>
        public static string column_SumCostPrice {
            get {
                return ResourceManager.GetString("column_SumCostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金额 的本地化字符串。
        /// </summary>
        public static string column_SumPrice {
            get {
                return ResourceManager.GetString("column_SumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 利润合计 的本地化字符串。
        /// </summary>
        public static string column_SumProfit {
            get {
                return ResourceManager.GetString("column_SumProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工时费合计 的本地化字符串。
        /// </summary>
        public static string column_SumServicePrice {
            get {
                return ResourceManager.GetString("column_SumServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商 的本地化字符串。
        /// </summary>
        public static string column_Supplier {
            get {
                return ResourceManager.GetString("column_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        public static string column_Unit {
            get {
                return ResourceManager.GetString("column_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单价 的本地化字符串。
        /// </summary>
        public static string column_UnitPrice {
            get {
                return ResourceManager.GetString("column_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 费用明细 的本地化字符串。
        /// </summary>
        public static string Header_ChargeDetail {
            get {
                return ResourceManager.GetString("Header_ChargeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 费用报表 的本地化字符串。
        /// </summary>
        public static string Header_ChargeReport {
            get {
                return ResourceManager.GetString("Header_ChargeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备品牌： 的本地化字符串。
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配件合计： 的本地化字符串。
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址: 的本地化字符串。
        /// </summary>
        public static string tb_Address {
            get {
                return ResourceManager.GetString("tb_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维修人员： 的本地化字符串。
        /// </summary>
        public static string tb_Attendant {
            get {
                return ResourceManager.GetString("tb_Attendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经办人: 的本地化字符串。
        /// </summary>
        public static string tb_AttendantName {
            get {
                return ResourceManager.GetString("tb_AttendantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别: 的本地化字符串。
        /// </summary>
        public static string tb_Category {
            get {
                return ResourceManager.GetString("tb_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 费用名称: 的本地化字符串。
        /// </summary>
        public static string tb_ChargeName {
            get {
                return ResourceManager.GetString("tb_ChargeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人: 的本地化字符串。
        /// </summary>
        public static string tb_Contact {
            get {
                return ResourceManager.GetString("tb_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成本价: 的本地化字符串。
        /// </summary>
        public static string tb_CostPrice {
            get {
                return ResourceManager.GetString("tb_CostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称: 的本地化字符串。
        /// </summary>
        public static string tb_CustomerName {
            get {
                return ResourceManager.GetString("tb_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期: 的本地化字符串。
        /// </summary>
        public static string tb_Date {
            get {
                return ResourceManager.GetString("tb_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单号： 的本地化字符串。
        /// </summary>
        public static string tb_DH {
            get {
                return ResourceManager.GetString("tb_DH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只显示数量不为零的货品 的本地化字符串。
        /// </summary>
        public static string tb_DisplayNoZero {
            get {
                return ResourceManager.GetString("tb_DisplayNoZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发动机号： 的本地化字符串。
        /// </summary>
        public static string tb_EngineID {
            get {
                return ResourceManager.GetString("tb_EngineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号: 的本地化字符串。
        /// </summary>
        public static string tb_ID {
            get {
                return ResourceManager.GetString("tb_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整机编号: 的本地化字符串。
        /// </summary>
        public static string tb_MachineID {
            get {
                return ResourceManager.GetString("tb_MachineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备厂家: 的本地化字符串。
        /// </summary>
        public static string tb_ManufacturerName {
            get {
                return ResourceManager.GetString("tb_ManufacturerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注： 的本地化字符串。
        /// </summary>
        public static string tb_Note {
            get {
                return ResourceManager.GetString("tb_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量: 的本地化字符串。
        /// </summary>
        public static string tb_Number {
            get {
                return ResourceManager.GetString("tb_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 厂码: 的本地化字符串。
        /// </summary>
        public static string tb_PDM {
            get {
                return ResourceManager.GetString("tb_PDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系电话: 的本地化字符串。
        /// </summary>
        public static string tb_PhoneNumber {
            get {
                return ResourceManager.GetString("tb_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金额: 的本地化字符串。
        /// </summary>
        public static string tb_Price {
            get {
                return ResourceManager.GetString("tb_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车型/发动机: 的本地化字符串。
        /// </summary>
        public static string tb_ProductCategory {
            get {
                return ResourceManager.GetString("tb_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配件名称： 的本地化字符串。
        /// </summary>
        public static string tb_ProductName {
            get {
                return ResourceManager.GetString("tb_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配件利润： 的本地化字符串。
        /// </summary>
        public static string tb_ProductProfit {
            get {
                return ResourceManager.GetString("tb_ProductProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均进货单价： 的本地化字符串。
        /// </summary>
        public static string tb_PurchaseCostPrice {
            get {
                return ResourceManager.GetString("tb_PurchaseCostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库单号： 的本地化字符串。
        /// </summary>
        public static string tb_PurchaseID {
            get {
                return ResourceManager.GetString("tb_PurchaseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拼音简码: 的本地化字符串。
        /// </summary>
        public static string tb_PY {
            get {
                return ResourceManager.GetString("tb_PY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库单号： 的本地化字符串。
        /// </summary>
        public static string tb_RKDH {
            get {
                return ResourceManager.GetString("tb_RKDH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售单价: 的本地化字符串。
        /// </summary>
        public static string tb_SaleUnitPrice {
            get {
                return ResourceManager.GetString("tb_SaleUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维修项目： 的本地化字符串。
        /// </summary>
        public static string tb_Service {
            get {
                return ResourceManager.GetString("tb_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总金额： 的本地化字符串。
        /// </summary>
        public static string tb_Sum {
            get {
                return ResourceManager.GetString("tb_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大写: 的本地化字符串。
        /// </summary>
        public static string tb_SumCaptalPrice {
            get {
                return ResourceManager.GetString("tb_SumCaptalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配件成本： 的本地化字符串。
        /// </summary>
        public static string tb_SumCostPrice {
            get {
                return ResourceManager.GetString("tb_SumCostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计: 的本地化字符串。
        /// </summary>
        public static string tb_SumPrice {
            get {
                return ResourceManager.GetString("tb_SumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 利润合计： 的本地化字符串。
        /// </summary>
        public static string tb_SumProfit {
            get {
                return ResourceManager.GetString("tb_SumProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计进货金额: 的本地化字符串。
        /// </summary>
        public static string tb_SumPurchaseCostPrice {
            get {
                return ResourceManager.GetString("tb_SumPurchaseCostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计进货数量： 的本地化字符串。
        /// </summary>
        public static string tb_SumPurchaseCount {
            get {
                return ResourceManager.GetString("tb_SumPurchaseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计销售成本: 的本地化字符串。
        /// </summary>
        public static string tb_SumSaleCostPrice {
            get {
                return ResourceManager.GetString("tb_SumSaleCostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计销售数量： 的本地化字符串。
        /// </summary>
        public static string tb_SumSaleCount {
            get {
                return ResourceManager.GetString("tb_SumSaleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配件合计： 的本地化字符串。
        /// </summary>
        public static string tb_SumSalePrice {
            get {
                return ResourceManager.GetString("tb_SumSalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工时费合计： 的本地化字符串。
        /// </summary>
        public static string tb_SumServicePrice {
            get {
                return ResourceManager.GetString("tb_SumServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商： 的本地化字符串。
        /// </summary>
        public static string tb_Supplier {
            get {
                return ResourceManager.GetString("tb_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位: 的本地化字符串。
        /// </summary>
        public static string tb_Unit {
            get {
                return ResourceManager.GetString("tb_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单价: 的本地化字符串。
        /// </summary>
        public static string tb_UnitPrice {
            get {
                return ResourceManager.GetString("tb_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售单号： 的本地化字符串。
        /// </summary>
        public static string tb_XSDH {
            get {
                return ResourceManager.GetString("tb_XSDH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲靖明德工程机械配件经营部——&gt;费用管理 的本地化字符串。
        /// </summary>
        public static string Title_ChargeView {
            get {
                return ResourceManager.GetString("Title_ChargeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲靖明德工程机械配件经营部——&gt;客户管理 的本地化字符串。
        /// </summary>
        public static string Title_CustomerView {
            get {
                return ResourceManager.GetString("Title_CustomerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲靖明德工程机械配件经营部 的本地化字符串。
        /// </summary>
        public static string Title_MainView {
            get {
                return ResourceManager.GetString("Title_MainView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲靖明德工程机械配件经营部——&gt;进货入库 的本地化字符串。
        /// </summary>
        public static string Title_NewPurchaseView {
            get {
                return ResourceManager.GetString("Title_NewPurchaseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲靖明德工程机械配件经营部——&gt;销售开单 的本地化字符串。
        /// </summary>
        public static string Title_NewSaleView {
            get {
                return ResourceManager.GetString("Title_NewSaleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲靖明德工程机械配件经营部——&gt;货品报表 的本地化字符串。
        /// </summary>
        public static string Title_ProductReportView {
            get {
                return ResourceManager.GetString("Title_ProductReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲靖明德工程机械配件经营部——&gt;货品管理 的本地化字符串。
        /// </summary>
        public static string Title_ProductView {
            get {
                return ResourceManager.GetString("Title_ProductView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲靖明德工程机械配件经营部——&gt;入库报表 的本地化字符串。
        /// </summary>
        public static string Title_PurchaseReportView {
            get {
                return ResourceManager.GetString("Title_PurchaseReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲靖明德工程机械配件经营部——&gt;入库管理 的本地化字符串。
        /// </summary>
        public static string Title_PurchaseView {
            get {
                return ResourceManager.GetString("Title_PurchaseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲靖明德工程机械配件经营部——&gt;销售报表 的本地化字符串。
        /// </summary>
        public static string Title_SaleReportView {
            get {
                return ResourceManager.GetString("Title_SaleReportView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲靖明德工程机械配件经营部——&gt;销售管理 的本地化字符串。
        /// </summary>
        public static string Title_SaleView {
            get {
                return ResourceManager.GetString("Title_SaleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲靖明德工程机械配件经营部——&gt;维修项目管理 的本地化字符串。
        /// </summary>
        public static string Title_ServiceView {
            get {
                return ResourceManager.GetString("Title_ServiceView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲靖明德工程机械配件经营部——&gt;供应商管理 的本地化字符串。
        /// </summary>
        public static string Title_SupplierView {
            get {
                return ResourceManager.GetString("Title_SupplierView", resourceCulture);
            }
        }
    }
}
